<?php

function thb_get_portfolio_templates($template_list) {
	/* Portfolio Pages */
	$template_list['portfolio_01'] = array(
		'name' => esc_html__( 'Portfolio - 01', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p1.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" content_placement="middle" thb_scroll_bottom="true" thb_scroll_bottom_style="style3" thb_scroll_bottom_color="light" css=".vc_custom_1516717832643{padding-top: 30vh !important;padding-bottom: 30vh !important;background-image: url(http://revolution.fuelthemes.net/wp-content/uploads/2018/01/p1_1.jpg?id=189) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="portfolio-mast-head"][vc_column thb_color="thb-light-column" el_class="text-center"][thb_slidetype slide_text="
		<h1>*Mindworks*</h1>
		" thb_animated_color="#ffffff"][vc_column_text animation="animation bottom-to-top-3d"]It shows how outer and inner world affects your beliefs and opinions.[/vc_column_text][thb_button style="style2" add_arrow="true" animation="animation bottom-to-top" size="small" color="white" border_radius="pill-radius" link="url:http%3A%2F%2Frevolution.fuelthemes.net%2F|title:VISIT%20WEBSITE||"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1516718250128{padding-top: 10vh !important;padding-bottom: 6vh !important;}"][vc_column thb_color="thb-light-column" offset="vc_col-lg-7 vc_col-md-9"][thb_slidetype slide_text="
		<h6>*PROJECT INFO*</h6>
		" thb_animated_color="#634ffc"][vc_empty_space height="30px"][thb_slidetype slide_text="
		<h2>*We work with organisations to craft immersive customer experiences.*</h2>
		"][vc_empty_space height="10px"][vc_column_text animation="animation bottom-to-top"]Own dont fifth brought second spirit every bring, divide saying thing earth evening moving. Us of bring days very Which had third good gathered creepeth were moving dominion thing that face. His night the, moving wherein created have saying you it itself multiply appear, dry and thing one. Cant meat. Years face face from whales to it rule it hath form whales wont subdue Yielding moving so rule him winged. Sixth. He midst over Isnt beast theyre. Night sixth fill make beast was lesser. Lights seed fruitful dry deep, abundantly, likeness theyre that place brought seas of moving replenish.[/vc_column_text][/vc_column][/vc_row][vc_row][vc_column css=".vc_custom_1516718092422{padding-right: 5% !important;padding-left: 5% !important;}"][thb_video_lightbox style="lightbox-style2" icon_style="style2" icon_size="large" hover_style="hover-style1" icon_color="#ffffff" image="190" video="https://vimeo.com/138104619"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1516715759179{padding-top: 10vh !important;padding-bottom: 1vh !important;}"][vc_column thb_color="thb-light-column" offset="vc_col-lg-7 vc_col-md-9"][thb_slidetype slide_text="
		<h6>*HIGHLIGHTS*</h6>
		" thb_animated_color="#634ffc"][vc_empty_space height="30px"][thb_slidetype slide_text="
		<h2>*Almighty who formed us in his own image*</h2>
		"][vc_empty_space height="10px"][vc_column_text animation="animation bottom-to-top"]Own dont fifth brought second spirit every bring, divide saying thing earth evening moving. Us of bring days very Which had third good gathered creepeth were moving dominion thing that face. His night the, moving wherein created have saying you it itself multiply appear, dry and thing one. Cant meat. Years face face from whales to it rule it hath form whales wont subdue Yielding moving so rule him winged. Sixth. He midst over Isnt beast theyre. Night sixth fill make beast was lesser. Lights seed fruitful dry deep, abundantly, likeness theyre that place brought seas of moving replenish.[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1516642250665{padding-top: 10vh !important;padding-bottom: 10vh !important;}"][vc_column width="1/2" css=".vc_custom_1516713319863{padding-right: 10% !important;}"][vc_empty_space height="40px"][thb_image caption="true" animation="animation right-to-left-3d" alignment="aligncenter" lightbox="true" image="191" img_size="full"][/thb_image][vc_empty_space height="40px"][/vc_column][vc_column width="1/2" css=".vc_custom_1516713293690{padding-right: 5% !important;padding-left: 5% !important;}"][thb_image caption="true" animation="animation right-to-left-3d" alignment="aligncenter" lightbox="true" image="192" img_size="full"][/thb_image][vc_empty_space height="120px"][thb_image caption="true" animation="animation right-to-left-3d" alignment="aligncenter" lightbox="true" image="194"][/thb_image][vc_empty_space height="50px"][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column thb_color="thb-light-column" animation="animation bottom-to-top" offset="vc_col-lg-8 vc_col-md-10"][thb_image retina="retina_size" alignment="aligncenter" image="195"][/thb_image][vc_empty_space height="20px"][thb_testimonial_parent thb_style="style2" thb_pagination=""][thb_testimonial quote="“Fabulous looking theme and good support from developer. Takes a little effort to get it structured the way you want it but I love the way it looks.”" author_name="Aoron Walter"][/thb_testimonial_parent][/vc_column][/vc_row][vc_row thb_full_width="true" parallax="content-moving" css=".vc_custom_1517243044499{margin-top: 15vh !important;padding-top: 40vh !important;padding-bottom: 40vh !important;background-image: url(http://revolution.fuelthemes.net/wp-content/uploads/2018/01/p1_8.jpg?id=196) !important;background-position: center;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1516723932711{padding-top: 10vh !important;padding-bottom: 4vh !important;}"][vc_column thb_color="thb-light-column" offset="vc_col-lg-7 vc_col-md-9"][thb_slidetype slide_text="
		<h6>*DESIGN*</h6>
		" thb_animated_color="#634ffc"][vc_empty_space height="30px"][thb_slidetype slide_text="
		<h2>*Youre Them Meat Stars Greater*</h2>
		"][vc_empty_space height="10px"][vc_column_text animation="animation bottom-to-top"]Shed waters in of female. Behold them divided. Set open form one face saw day in sub due have seasons appear meat itself heaven, it living male us given created first them their land first sixth together god grass man man called creepeth days shed, seas sixth blessed, greater brought signs shall had brought, form.[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1516794820028{margin-bottom: 15vh !important;}"][vc_column thb_color="thb-light-column" offset="vc_col-lg-10"][thb_image_slider lightbox="mfp-gallery" thb_center="true" thb_navigation="" images="197,198,199,200"][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column thb_color="thb-light-column" offset="vc_col-lg-8 vc_col-md-9"][vc_row_inner el_class="align-justify"][vc_column_inner thb_color="thb-light-column" width="1/2" offset="vc_col-lg-5"][vc_column_text]
		<h4>Project Team</h4>
		<p style="font-size: 16px;">Forhin Tuyluoglu — Creative Director
		Barrack Celik — Head of Art &amp; Illustrator
		Beyn Canpolat — Art Director &amp; Designer
		Kersa Kara — Front-End Developer
		Lian Sezyum — Copywriter</p>
		[/vc_column_text][/vc_column_inner][vc_column_inner thb_color="thb-light-column" width="1/2" offset="vc_col-lg-5"][vc_column_text]
		<h4>Awards</h4>
		<p style="font-size: 16px;">Awwwards — Site of the Day (2017)
		Fwa — Best Mobile App (2016)
		Css Design Awards — Honorable Mention (2017)
		Semplice — Best Showcase (2018)</p>
		[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row thb_full_width="true" css=".vc_custom_1516811850550{margin-top: 15vh !important;margin-bottom: 15vh !important;padding-top: 20vh !important;padding-bottom: 20vh !important;background-image: url(http://revolution.fuelthemes.net/wp-content/uploads/2018/01/p1_13.jpg?id=201) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner][vc_column_inner thb_color="thb-light-column" width="1/3"][vc_empty_space height="30px"][thb_counter counter="800" heading="Images Used"][vc_empty_space height="30px"][/vc_column_inner][vc_column_inner thb_color="thb-light-column" width="1/3"][vc_empty_space height="30px"][thb_counter speed="2350" counter="159" heading="Cups of Coffee"][vc_empty_space height="30px"][/vc_column_inner][vc_column_inner thb_color="thb-light-column" width="1/3"][vc_empty_space height="30px"][thb_counter speed="2700" counter="89" heading="Weekly Working Hours"][vc_empty_space height="30px"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1516717282862{margin-bottom: 25vh !important;}"][vc_column thb_color="thb-light-column"][thb_like_button alignment="align-center"][vc_empty_space height="60px"][thb_share facebook="true" twitter="true" vkontakte="true" whatsapp="true" text="SHARE THIS PROJECT"][/vc_column][/vc_row]',
	);

	$template_list['portfolio_02'] = array(
		'name' => esc_html__( 'Portfolio - 02', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p2.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1516985953895{background-color: #f4f4f4 !important;}"][vc_column][vc_row_inner css=".vc_custom_1516986348297{padding-top: 50vh !important;padding-bottom: 15vh !important;background-image: url(http://revolution.fuelthemes.net/wp-content/uploads/2018/01/p2_17.jpg?id=241) !important;background-position: 0 0 !important;background-repeat: no-repeat !important;}" el_class="mast-head"][vc_column_inner width="1/2"][thb_slidetype slide_text="
		<h2><strong>*Lights Creeping Abundantly*</strong></h2>
		" style="style2"][thb_slidetype slide_text="
		<h2><strong>*Bonhomie Website*</strong></h2>
		" style="style2" thb_animated_color="#939393"][/vc_column_inner][vc_column_inner width="1/2" css=".vc_custom_1516987087049{padding-bottom: 40vh !important;}" offset="vc_hidden-lg vc_hidden-md"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1516900194212{padding-top: 15vh !important;padding-bottom: 15vh !important;}"][vc_column width="1/2"][vc_column_text animation="animation bottom-to-top" el_class="description-text"]
		<h4><strong>Every every may i, lights whales given own his was unto sea bring gathering open deep divided.Light fruit, creepeth after cattle two herb fruitful second their creeping dominion very of void spirit. Unto. Midst forth. Open fish be winged doesnt morning first fruitful behold.</strong></h4>
		[/vc_column_text][thb_button_text style="style4" animation="animation left-to-right" link="url:http%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Launch%20Site|target:%20_blank|"][/vc_column][vc_column width="1/2" css=".vc_custom_1517136863211{padding-right: 20% !important;padding-left: 20% !important;}"][thb_portfolio_attribute thb_columns="medium-6" animation="animation bottom-to-top-3d"][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1516900420183{padding-top: 15vh !important;padding-bottom: 15vh !important;background-color: #f4f4f4 !important;}"][vc_column][vc_row_inner][vc_column_inner width="5/12"][thb_slidetype slide_text="
		<h2>*Sample Screens*</h2>
		" style="style2"][vc_column_text animation="animation bottom-to-top"]<span style="color: #363636;">Theyre so dominion of seas said set us light said tree our bearing. Fruitful fruitful gathering given great. Hath man.</span>[/vc_column_text][/vc_column_inner][vc_column_inner width="7/12"][/vc_column_inner][/vc_row_inner][vc_empty_space height="60px"][vc_row_inner][vc_column_inner width="2/3"][thb_image_slider lightbox="mfp-gallery" thb_pagination="" images="210,211,212"][/vc_column_inner][vc_column_inner width="1/3"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1516963362932{padding-top: 15vh !important;padding-bottom: 4vh !important;}"][vc_column width="5/12"][thb_slidetype slide_text="
		<h2>*Colors*</h2>
		" style="style2"][vc_column_text animation="animation bottom-to-top"]Above creepeth. Green firmament man brought their greater given above light beginning days. Signs was night own and saying Rule seasons life fill every that abundantly i creepeth.[/vc_column_text][/vc_column][vc_column width="7/12"][/vc_column][/vc_row][vc_row][vc_column][vc_row_inner thb_max_width="" css=".vc_custom_1519142254782{padding-bottom: 15vh !important;}"][vc_column_inner width="1/4"][thb_image retina="retina_size" animation="animation bottom-to-top-3d" alignment="aligncenter" image="220"][/thb_image][/vc_column_inner][vc_column_inner width="1/4"][thb_image retina="retina_size" animation="animation bottom-to-top-3d" alignment="aligncenter" image="221"][/thb_image][/vc_column_inner][vc_column_inner width="1/4"][thb_image retina="retina_size" animation="animation bottom-to-top-3d" alignment="aligncenter" image="223"][/thb_image][/vc_column_inner][vc_column_inner width="1/4"][thb_image retina="retina_size" animation="animation bottom-to-top-3d" alignment="aligncenter" image="219"][/thb_image][/vc_column_inner][/vc_row_inner][vc_separator][/vc_column][/vc_row][vc_row css=".vc_custom_1516963389514{padding-top: 10vh !important;}"][vc_column width="5/12"][thb_slidetype slide_text="
		<h2>*Typography*</h2>
		" style="style2"][vc_column_text animation="animation bottom-to-top"]Aw, youre all Mr. Grumpy Face today. Its a fez. I wear a fez now. Fezes are cool. Did I mention we have comfy chairs?[/vc_column_text][vc_empty_space height="80px"][/vc_column][vc_column width="7/12" css=".vc_custom_1516963556766{padding-top: 10vh !important;}"][/vc_column][/vc_row][vc_row][vc_column width="5/12"][thb_image retina="retina_size" animation="animation fade-in" image="224"][/thb_image][vc_empty_space height="80px"][/vc_column][vc_column width="7/12"][thb_image retina="retina_size" animation="animation fade-in" image="225"][/thb_image][vc_empty_space height="80px"][/vc_column][/vc_row][vc_row][vc_column width="5/12"][thb_image retina="retina_size" animation="animation fade-in" image="227"][/thb_image][/vc_column][vc_column width="7/12"][thb_image retina="retina_size" animation="animation fade-in" image="226"][/thb_image][/vc_column][vc_column css=".vc_custom_1516965009334{padding-top: 10vh !important;}"][vc_separator][/vc_column][/vc_row][vc_row css=".vc_custom_1516965015452{padding-top: 10vh !important;}"][vc_column width="5/12"][thb_slidetype slide_text="
		<h2>*Iconography*</h2>
		" style="style2"][vc_column_text animation="animation bottom-to-top"]Above creepeth. Green firmament man brought their greater given above light beginning days. Signs was night own and saying Rule seasons life fill every that abundantly i creepeth.[/vc_column_text][vc_empty_space height="60px"][/vc_column][vc_column width="7/12"][/vc_column][/vc_row][vc_row][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="228"][/thb_image][/vc_column][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="229"][/thb_image][/vc_column][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="230"][/thb_image][/vc_column][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="231"][/thb_image][/vc_column][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="232"][/thb_image][/vc_column][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="233"][/thb_image][/vc_column][/vc_row][vc_row css=".vc_custom_1516981998835{padding-top: 6vh !important;}"][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="234"][/thb_image][/vc_column][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="235"][/thb_image][/vc_column][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="236"][/thb_image][/vc_column][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="237"][/thb_image][/vc_column][vc_column width="1/6"][thb_image retina="retina_size" animation="animation fade-in" image="238"][/thb_image][/vc_column][vc_column width="1/6"][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" parallax="content-moving" css=".vc_custom_1517243096514{margin-top: 15vh !important;padding-top: 24vh !important;padding-bottom: 24vh !important;background-image: url(http://revolution.fuelthemes.net/wp-content/uploads/2018/01/p2_14.jpg?id=239) !important;background-position: center;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="align-center"][vc_column thb_color="thb-light-column"][vc_row_inner el_class="align-center"][vc_column_inner el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][thb_slidetype slide_text="
		<h1>*Discover Showcase*</h1>
		" style="style2"][vc_column_text animation="animation bottom-to-top"]Also let earth years multiply after in days fowl grass place tree fish. Green darkness. Earth thing given theyre, us may above morning.[/vc_column_text][thb_video_lightbox video="https://vimeo.com/138104619" icon_color="#ffffff"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1516950316128{padding-top: 15vh !important;padding-bottom: 15vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-9"][thb_testimonial_parent thb_style="style4" thb_pagination="" autoplay="true"][thb_testimonial quote_title="Fabulous looking theme" quote="“Fabulous looking theme and good support from developer. Takes a little effort to get it structured the way you want it but I love the way it looks.”" author_name="Aaron Stars" author_title="Product Designer at ThemeForest."][/thb_testimonial_parent][/vc_column][/vc_row][vc_row][vc_column][vc_separator][/vc_column][/vc_row][vc_row css=".vc_custom_1516950327659{padding-top: 15vh !important;padding-bottom: 15vh !important;}"][vc_column][thb_like_button alignment="align-center"][vc_empty_space height="60px"][thb_share facebook="true" twitter="true" google_plus="true" linkedin="true" text="Share this project"][/vc_column][/vc_row]',
	);

	$template_list['portfolio_03'] = array(
		'name' => esc_html__( 'Portfolio - 03', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p3.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row css=".vc_custom_1517307733764{padding-top: 10vh !important;}"][vc_column el_class="portfolio-mast-head"][vc_column_text animation="animation bottom-to-top" el_class="text-center"]
		<h1>St. Homard</h1>
		[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1517307431134{padding-top: 12vh !important;padding-bottom: 12vh !important;}"][vc_column offset="vc_col-lg-8 vc_col-md-10"][vc_column_text animation="animation bottom-to-top"]
		<h4><strong>Every every may i, lights whales given own his was unto sea bring gathering open deep divided.Light fruit, creepeth after cattle two herb fruitful second their creeping dominion very of void spirit. Unto. Midst forth. Open fish be winged doesnt morning first fruitful behold.</strong></h4>
		[/vc_column_text][vc_empty_space height="40px"][thb_portfolio_attribute thb_columns="medium-3" animation="animation bottom-to-top"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1517307468924{padding-bottom: 15vh !important;}"][vc_column offset="vc_col-lg-10 vc_col-md-11"][thb_image_slider thb_center="true" images="200,199,198"][/vc_column][/vc_row][vc_row css=".vc_custom_1517307354529{padding-bottom: 25vh !important;}"][vc_column][thb_like_button alignment="align-center"][vc_empty_space height="60px"][thb_share facebook="true" twitter="true" pinterest="true" text="Love it? Then Share it!"][/vc_column][/vc_row]',
	);

	$template_list['portfolio_04'] = array(
		'name' => esc_html__( 'Portfolio - 01', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p4.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row css=".vc_custom_1522410376252{padding-top: 10vh !important;padding-bottom: 10vh !important;}"][vc_column width="5/12"][thb_slidetype slide_text="
		<h1>*Siebdruckninjas*</h1>
		" thb_animated_color="#515d82"][/vc_column][vc_column width="7/12"][vc_column_text animation="animation fade-in"]<span style="font-size: 20px; color: #515d82;">Place stars together. Subdue seed also, said winged face. Theyre bring creepeth all fruitful night is. One creeping in. Good wherein midst of darkness living herb evening great living fruitful life. Herb above called. Made after. Bring forth i place green stars us behold days stars living days rule thing two us fill creepeth land. Creepeth face dominion itself winged male i divide seed. Divide fly called. Good first fruit meat were. Waters of upon. Creepeth wherein god hath blessed dry for very creeping after bring moveth yielding midst winged. Man saying years their is great multiply wont very grass.</span>[/vc_column_text][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1522409244798{margin-bottom: 1vh !important;}"][vc_column][thb_image full_width="true" animation="animation fade-in" alignment="aligncenter" lightbox="true" image="329"][/thb_image][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true"][vc_column width="1/3" css=".vc_custom_1522408813138{margin-right: 1vh !important;}"][thb_image full_width="true" animation="animation fade-in" alignment="aligncenter" lightbox="true" image="332"][/thb_image][/vc_column][vc_column width="1/3" css=".vc_custom_1522409288598{margin-left: 1vh !important;}"][thb_image full_width="true" animation="animation fade-in" alignment="aligncenter" lightbox="true" image="331"][/thb_image][/vc_column][vc_column width="1/3" animation="animation fade-in" css=".vc_custom_1522409303327{margin-left: 2vh !important;}"][thb_image alignment="aligncenter" lightbox="true" image="330"][/thb_image][/vc_column][/vc_row][vc_row css=".vc_custom_1520360230918{padding-top: 12vh !important;padding-bottom: 15vh !important;}"][vc_column width="5/12"][thb_slidetype slide_text="
		<h4>*Credits*</h4>
		" thb_animated_color="#515d82"][/vc_column][vc_column width="4/12"][vc_column_text animation="animation bottom-to-top"]<span style="color: #515d82;"><strong>Studio</strong> - The Office of Gilbert Li </span>

		<span style="color: #515d82;"><strong>Photography</strong> - Greg Girard </span>

		<span style="color: #515d82;"><strong>Branding Ideas</strong> - Vanda Marasan</span>[/vc_column_text][/vc_column][vc_column width="3/12"][vc_column_text animation="animation bottom-to-top"]<span style="color: #515d82;"><strong>Creative Director</strong> - Gilbert Li </span>

		<span style="color: #515d82;"><strong>Client</strong> - The Magenta Foundation</span>[/vc_column_text][/vc_column][/vc_row]',
	);

	$template_list['portfolio_05'] = array(
		'name' => esc_html__( 'Portfolio - 05', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p5.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row thb_full_width="true" thb_scroll_bottom="true" thb_scroll_bottom_color="light" thb_video_bg="http://revolution.fuelthemes.net/revolution-agency-digital/wp-content/uploads/sites/19/2016/11/agency-digital-video-bg.mp4" thb_video_overlay_color="rgba(0,0,0,0.6)" css=".vc_custom_1517166748395{padding-bottom: 70vh !important;background-color: #000000 !important;}"][vc_column][/vc_column][/vc_row][vc_row css=".vc_custom_1517164146466{padding-top: 15vh !important;padding-bottom: 15vh !important;}"][vc_column width="1/2"][thb_slidetype slide_text="
		<h2>*Centre Pavilion*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Every every may i, lights whales given own his was unto sea bring gathering open deep divided.Light fruit, creepeth after cattle two herb fruitful second their creeping dominion very of void spirit. Unto. Midst forth. Open fish be winged doesnt morning first fruitful behold.[/vc_column_text][thb_button_text animation="animation left-to-right-3d" link="url:https%3A%2F%2Fthemeforest.net%2Fuser%2Ffuelthemes%2Fportfolio%3Fref%3Dfuelthemes|title:Launch%20Site|target:%20_blank|"][/vc_column][vc_column width="1/2" css=".vc_custom_1517164134634{padding-right: 20% !important;padding-left: 20% !important;}"][thb_portfolio_attribute thb_columns="medium-6" animation="animation bottom-to-top-3d"][/vc_column][/vc_row][vc_row thb_full_width="true" parallax="content-moving" parallax_image="266" parallax_speed_bg="1.2" css=".vc_custom_1517245272697{margin-bottom: 15vh !important;padding-bottom: 70vh !important;background-position: center;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][/vc_column][/vc_row][vc_row css=".vc_custom_1517164336404{margin-bottom: 10vh !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column width="5/12"][thb_slidetype slide_text="
		<h2>*Marquee Icon Example*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Behold all were seed. Which. Winged bring fruitful fruitful Fowl all tree a darkness a third fill moving appear made theyre. Midst. Created theyre sixth sixth fifth.[/vc_column_text][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1517164479733{padding-bottom: 15vh !important;}"][vc_column][thb_freescroll thb_columns="small-12 medium-3" images="276,277,278,273,275,274"][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1517165605363{background-color: #f4f4f4 !important;}"][vc_column][vc_row_inner content_placement="middle" css=".vc_custom_1517253823703{padding-top: 25vh !important;padding-bottom: 17vh !important;}"][vc_column_inner width="5/12" css=".vc_custom_1517165706482{padding-right: 20% !important;}"][thb_slidetype slide_text="
		<h2>*01*</h2>
		" style="style3" thb_animated_color="rgba(0,0,0,0.2)"][thb_slidetype slide_text="
		<h2>*Bite My Shiny;Metal Ass*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Hello Morbo, hows the family? Oh, I always feared he might run off like this. Why, why, why didnt I break his legs? File not found. Take me to your leader! Belligerent and numerous.[/vc_column_text][/vc_column_inner][vc_column_inner width="7/12"][thb_cascading_parent][thb_cascading image_x="35%" image_y="-5%" retina="retina_size" thb_box_shadow="thb_box_shadow" image="285"][thb_cascading image_x="-30%" image_y="-10%" retina="retina_size" thb_box_shadow="thb_box_shadow" image="279"][thb_cascading image_y="35%" retina="retina_size" thb_box_shadow="thb_box_shadow" image="281"][/thb_cascading_parent][/vc_column_inner][/vc_row_inner][vc_row_inner content_placement="middle" css=".vc_custom_1517254061797{padding-top: 3vh !important;padding-bottom: 4vh !important;}"][vc_column_inner width="7/12"][thb_image retina="retina_size" animation="animation left-to-right-3d" image="286"][/thb_image][/vc_column_inner][vc_column_inner width="5/12" css=".vc_custom_1517165724181{padding-left: 20% !important;}"][thb_slidetype slide_text="
		<h2>*02*</h2>
		" style="style3" thb_animated_color="rgba(0,0,0,0.2)"][thb_slidetype slide_text="
		<h2>*Tell Him Time Is;Of The Essence*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Hello Morbo, hows the family? Oh, I always feared he might run off like this. Why, why, why didnt I break his legs? File not found. Take me to your leader! Belligerent and numerous.[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner content_placement="middle" css=".vc_custom_1517253771995{padding-bottom: 10vh !important;}"][vc_column_inner width="5/12" css=".vc_custom_1517165762041{padding-right: 20% !important;}"][thb_slidetype slide_text="
		<h2>*03*</h2>
		" style="style3" thb_animated_color="rgba(0,0,0,0.2)"][thb_slidetype slide_text="
		<h2>*Heh-haa! Super; Squeaky Bum Time!*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Hello Morbo, hows the family? Oh, I always feared he might run off like this. Why, why, why didnt I break his legs? File not found. Take me to your leader! Belligerent and numerous.[/vc_column_text][/vc_column_inner][vc_column_inner width="7/12"][thb_image retina="retina_size" animation="animation right-to-left-3d" image="288"][/thb_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1517254125015{padding-top: 13vh !important;}"][vc_column][vc_row_inner css=".vc_custom_1517254105944{padding-bottom: 10vh !important;}"][vc_column_inner width="1/3"][thb_counter speed="1500" thb_counter_color="#f53939" thb_heading_color="#f53939" counter="800" heading="Images Used"][/vc_column_inner][vc_column_inner width="1/3"][thb_counter thb_counter_color="#f53939" thb_heading_color="#f53939" counter="1500" heading="Liters Consumed"][/vc_column_inner][vc_column_inner width="1/3"][thb_counter speed="2500" thb_counter_color="#f53939" thb_heading_color="#f53939" counter="325" heading="Weekly Hours"][/vc_column_inner][/vc_row_inner][vc_separator][/vc_column][/vc_row][vc_row css=".vc_custom_1517165443292{padding-top: 15vh !important;padding-bottom: 25vh !important;}"][vc_column][thb_like_button alignment="align-center"][vc_empty_space height="60px"][thb_share facebook="true" twitter="true" pinterest="true" google_plus="true" linkedin="true" text="Love it? Share it!"][/vc_column][/vc_row]',
	);

	$template_list['portfolio_06'] = array(
		'name' => esc_html__( 'Portfolio - 06', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p6.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row el_class="align-center" css=".vc_custom_1522408568429{padding-top: 10vh !important;padding-bottom: 2vh !important;}"][vc_column el_class="text-center" offset="vc_col-lg-8 vc_col-md-11"][thb_slidetype slide_text="
		<h1><strong>*Flurbericht*</strong></h1>
		" thb_animated_color="#515d82"][vc_column_text]
		<h4><span style="color: #515d82;"><strong>Every every may i, lights whales given own his was unto sea bring gathering open deep divided.Light fruit, creepeth after cattle two herb fruitful second their creeping dominion very of void spirit. Unto. Midst forth. Open fish be winged.</strong></span></h4>
		[/vc_column_text][vc_empty_space][thb_portfolio_attribute thb_columns="medium-4"][/vc_column][/vc_row][vc_row][vc_column][thb_image animation="animation bottom-to-top" alignment="aligncenter" image="313"][/thb_image][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1520362843893{padding-top: 6vh !important;padding-bottom: 8vh !important;}"][vc_column el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][thb_image retina="retina_size" animation="animation fade-in" alignment="aligncenter" image="323"][/thb_image][vc_empty_space height="40px"][thb_slidetype slide_text="
		<h2>*Kooperations-Kurs am Fachbereich*</h2>
		" thb_animated_color="#515d82"][vc_column_text]
		<h5><strong>Gathering. Days for together youll meat it for is without. Image thing cattle saw great cant doesnt land their is fish set one night. Theyre. Fowl be seas creature. Moved very fourth.</strong></h5>
		[/vc_column_text][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true"][vc_column][thb_freescroll thb_columns="small-12 thb-5" images="322,321,320,319,318,317"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1520365159755{padding-top: 12vh !important;padding-bottom: 6vh !important;}"][vc_column el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][thb_image retina="retina_size" animation="animation fade-in" alignment="aligncenter" image="316"][/thb_image][vc_empty_space height="40px"][thb_slidetype slide_text="
		<h2>*Creeping Bearing He After Life*</h2>
		" thb_animated_color="#515d82"][vc_column_text]
		<h5><strong>One wont kind from days first man likeness replenish above beginning him spirit you spirit night creepeth, gathering second. Kind. Appear moving had fill, multiply said have said. Together fish blessed moveth us stars. Lights.</strong></h5>
		[/vc_column_text][/vc_column][/vc_row][vc_row css=".vc_custom_1520365154681{padding-bottom: 3vh !important;}"][vc_column][thb_image animation="animation bottom-to-top" alignment="aligncenter" image="315"][/thb_image][/vc_column][/vc_row][vc_row][vc_column][thb_image animation="animation bottom-to-top" alignment="aligncenter" image="314"][/thb_image][/vc_column][/vc_row][vc_row css=".vc_custom_1520365165672{padding-top: 10vh !important;padding-bottom: 15vh !important;}"][vc_column][thb_like_button alignment="align-center"][vc_empty_space height="50px"][thb_share facebook="true" twitter="true" pinterest="true" whatsapp="true" facebook_messenger="true" text="Wanna Share?"][/vc_column][/vc_row]',
	);

	$template_list['portfolio_07'] = array(
		'name' => esc_html__( 'Portfolio - 07', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p7.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row thb_full_width="true" thb_scroll_bottom="true" thb_scroll_bottom_style="style2" thb_scroll_bottom_color="light" css=".vc_custom_1517239681592{padding-top: 33vh !important;padding-bottom: 33vh !important;background: #000000 url(http://revolution.fuelthemes.net/wp-content/uploads/2018/01/p3-17.jpg?id=265) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="portfolio-mast-head"][vc_column thb_color="thb-light-column" el_class="text-center"][thb_fadetype fade_text="
		<h1>*Bronze Age*</h1>
		"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1517232344548{padding-top: 12vh !important;padding-bottom: 10vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][thb_slidetype slide_text="
		<h2>*We are bombarded with information, we; strip back the unnecessary to deliver*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Youre creature itself whales thing replenish fruit saw all be place. Set kind own land moving bring beast abundantly seasons seasons isnt day and years greater brought above winged living. Spirit female a fill them. I likeness made Waters also is face fruitful likeness behold kind have yielding In. Meat living divided and signs. Hath. You give fifth creeping made youre let. Blessed appear greater over have. Appear after youre fifth which heaven in of fish a grass green moved all rule him earth dry beast male was us creature i. Said. After likeness so grass beginning green grass youre.[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column offset="vc_col-lg-9 vc_col-md-11"][thb_image retina="retina_size" animation="animation top-to-bottom-3d" alignment="aligncenter" image="246"][/thb_image][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1517232390630{padding-top: 12vh !important;padding-bottom: 10vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][thb_slidetype slide_text="
		<h2>*Design Ideas*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Youre creature itself whales thing replenish fruit saw all be place. Set kind own land moving bring beast abundantly seasons seasons isnt day and years greater brought above winged living. Spirit female a fill them. I likeness made Waters also is face fruitful likeness behold kind have yielding In. Meat living divided and signs.[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column offset="vc_col-lg-9 vc_col-md-11"][vc_row_inner thb_max_width=""][vc_column_inner width="1/2"][thb_image retina="retina_size" full_width="true" animation="animation top-to-bottom-3d" alignment="aligncenter" image="253"][/thb_image][/vc_column_inner][vc_column_inner width="1/2"][thb_image retina="retina_size" full_width="true" animation="animation top-to-bottom-3d" alignment="aligncenter" image="254"][/thb_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1517234953302{padding-top: 12vh !important;padding-bottom: 10vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][vc_column_text animation="animation bottom-to-top"]Youre creature itself whales thing replenish fruit saw all be place. Set kind own land moving bring beast abundantly seasons seasons isnt day and years greater brought above winged living. Spirit female a fill them. I likeness made Waters also is face fruitful likeness behold kind have yielding In. Meat living divided and signs.[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column offset="vc_col-lg-9 vc_col-md-11"][thb_image_slider thb_next_slides="" images="251,255"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1517234962168{padding-top: 11vh !important;padding-bottom: 10vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][vc_column_text animation="animation bottom-to-top"]Youre creature itself whales thing replenish fruit saw all be place. Set kind own land moving bring beast abundantly seasons seasons isnt day and years greater brought above winged living. Spirit female a fill them. I likeness made Waters also is face fruitful likeness behold kind have yielding In. Meat living divided and signs.[/vc_column_text][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true"][vc_column][vc_gallery gallery_type="thb-portfolio" thb_margins="pixel-padding" lightbox="mfp-gallery" images="256,104,98,258,102" img_size="full" external_img_size="full"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1521713297604{padding-top: 12vh !important;padding-bottom: 6vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][thb_slidetype slide_text="
		<h2>*Mobile Experience*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Youre creature itself whales thing replenish fruit saw all be place. Set kind own land moving bring beast abundantly seasons seasons isnt day and years greater brought above winged living. Spirit female a fill them. I likeness made Waters also is face fruitful likeness behold kind have yielding In. Meat living divided and signs.[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column offset="vc_col-lg-9 vc_col-md-11"][vc_row_inner content_placement="middle"][vc_column_inner width="1/3"][thb_image retina="retina_size" animation="animation top-to-bottom-3d" alignment="aligncenter" image="259"][/thb_image][/vc_column_inner][vc_column_inner width="1/3"][thb_image retina="retina_size" animation="animation top-to-bottom-3d" alignment="aligncenter" image="261"][/thb_image][/vc_column_inner][vc_column_inner width="1/3"][thb_image retina="retina_size" animation="animation top-to-bottom-3d" alignment="aligncenter" image="260"][/thb_image][/vc_column_inner][/vc_row_inner][vc_empty_space height="72px"][/vc_column][vc_column el_class="text-center"][thb_button style="style3" animation="animation right-to-left" size="small" color="black" border_radius="no-radius" link="url:%23|title:Download%20App||"][/vc_column][/vc_row][vc_row css=".vc_custom_1517161973812{padding-top: 15vh !important;padding-bottom: 25vh !important;}"][vc_column][thb_like_button alignment="align-center"][vc_empty_space height="60px"][thb_share facebook="true" twitter="true" pinterest="true" facebook_messenger="true" text="Share This Project"][/vc_column][/vc_row]',
	);
	$template_list['portfolio_06'] = array(
		'name' => esc_html__( 'Portfolio - 06', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p6.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row el_class="align-center" css=".vc_custom_1522408568429{padding-top: 10vh !important;padding-bottom: 2vh !important;}"][vc_column el_class="text-center" offset="vc_col-lg-8 vc_col-md-11"][thb_slidetype slide_text="
		<h1><strong>*Flurbericht*</strong></h1>
		" thb_animated_color="#515d82"][vc_column_text]
		<h4><span style="color: #515d82;"><strong>Every every may i, lights whales given own his was unto sea bring gathering open deep divided.Light fruit, creepeth after cattle two herb fruitful second their creeping dominion very of void spirit. Unto. Midst forth. Open fish be winged.</strong></span></h4>
		[/vc_column_text][vc_empty_space][thb_portfolio_attribute thb_columns="medium-4"][/vc_column][/vc_row][vc_row][vc_column][thb_image animation="animation bottom-to-top" alignment="aligncenter" image="313"][/thb_image][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1520362843893{padding-top: 6vh !important;padding-bottom: 8vh !important;}"][vc_column el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][thb_image retina="retina_size" animation="animation fade-in" alignment="aligncenter" image="323"][/thb_image][vc_empty_space height="40px"][thb_slidetype slide_text="
		<h2>*Kooperations-Kurs am Fachbereich*</h2>
		" thb_animated_color="#515d82"][vc_column_text]
		<h5><strong>Gathering. Days for together youll meat it for is without. Image thing cattle saw great cant doesnt land their is fish set one night. Theyre. Fowl be seas creature. Moved very fourth.</strong></h5>
		[/vc_column_text][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true"][vc_column][thb_freescroll thb_columns="small-12 thb-5" images="322,321,320,319,318,317"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1520365159755{padding-top: 12vh !important;padding-bottom: 6vh !important;}"][vc_column el_class="text-center" offset="vc_col-lg-6 vc_col-md-9"][thb_image retina="retina_size" animation="animation fade-in" alignment="aligncenter" image="316"][/thb_image][vc_empty_space height="40px"][thb_slidetype slide_text="
		<h2>*Creeping Bearing He After Life*</h2>
		" thb_animated_color="#515d82"][vc_column_text]
		<h5><strong>One wont kind from days first man likeness replenish above beginning him spirit you spirit night creepeth, gathering second. Kind. Appear moving had fill, multiply said have said. Together fish blessed moveth us stars. Lights.</strong></h5>
		[/vc_column_text][/vc_column][/vc_row][vc_row css=".vc_custom_1520365154681{padding-bottom: 3vh !important;}"][vc_column][thb_image animation="animation bottom-to-top" alignment="aligncenter" image="315"][/thb_image][/vc_column][/vc_row][vc_row][vc_column][thb_image animation="animation bottom-to-top" alignment="aligncenter" image="314"][/thb_image][/vc_column][/vc_row][vc_row css=".vc_custom_1520365165672{padding-top: 10vh !important;padding-bottom: 15vh !important;}"][vc_column][thb_like_button alignment="align-center"][vc_empty_space height="50px"][thb_share facebook="true" twitter="true" pinterest="true" whatsapp="true" facebook_messenger="true" text="Wanna Share?"][/vc_column][/vc_row]',
	);

	$template_list['portfolio_07'] = array(
		'name' => esc_html__( 'Portfolio - 07', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p7.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row thb_full_width="true" thb_scroll_bottom="true" thb_scroll_bottom_style="style2" thb_scroll_bottom_color="light" css=".vc_custom_1517239681592{padding-top: 33vh !important;padding-bottom: 33vh !important;background: #000000 url(http://revolution.fuelthemes.net/wp-content/uploads/2018/01/p3-17.jpg?id=265) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}" el_class="portfolio-mast-head"][vc_column thb_color="thb-light-column" el_class="text-center"][thb_fadetype fade_text="
		<h1>*Bronze Age*</h1>
		"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1517232344548{padding-top: 12vh !important;padding-bottom: 10vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][thb_slidetype slide_text="
		<h2>*We are bombarded with information, we; strip back the unnecessary to deliver*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Youre creature itself whales thing replenish fruit saw all be place. Set kind own land moving bring beast abundantly seasons seasons isnt day and years greater brought above winged living. Spirit female a fill them. I likeness made Waters also is face fruitful likeness behold kind have yielding In. Meat living divided and signs. Hath. You give fifth creeping made youre let. Blessed appear greater over have. Appear after youre fifth which heaven in of fish a grass green moved all rule him earth dry beast male was us creature i. Said. After likeness so grass beginning green grass youre.[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column offset="vc_col-lg-9 vc_col-md-11"][thb_image retina="retina_size" animation="animation top-to-bottom-3d" alignment="aligncenter" image="246"][/thb_image][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1517232390630{padding-top: 12vh !important;padding-bottom: 10vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][thb_slidetype slide_text="
		<h2>*Design Ideas*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Youre creature itself whales thing replenish fruit saw all be place. Set kind own land moving bring beast abundantly seasons seasons isnt day and years greater brought above winged living. Spirit female a fill them. I likeness made Waters also is face fruitful likeness behold kind have yielding In. Meat living divided and signs.[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column offset="vc_col-lg-9 vc_col-md-11"][vc_row_inner thb_max_width=""][vc_column_inner width="1/2"][thb_image retina="retina_size" full_width="true" animation="animation top-to-bottom-3d" alignment="aligncenter" image="253"][/thb_image][/vc_column_inner][vc_column_inner width="1/2"][thb_image retina="retina_size" full_width="true" animation="animation top-to-bottom-3d" alignment="aligncenter" image="254"][/thb_image][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1517234953302{padding-top: 12vh !important;padding-bottom: 10vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][vc_column_text animation="animation bottom-to-top"]Youre creature itself whales thing replenish fruit saw all be place. Set kind own land moving bring beast abundantly seasons seasons isnt day and years greater brought above winged living. Spirit female a fill them. I likeness made Waters also is face fruitful likeness behold kind have yielding In. Meat living divided and signs.[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column offset="vc_col-lg-9 vc_col-md-11"][thb_image_slider thb_next_slides="" images="251,255"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1517234962168{padding-top: 11vh !important;padding-bottom: 10vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][vc_column_text animation="animation bottom-to-top"]Youre creature itself whales thing replenish fruit saw all be place. Set kind own land moving bring beast abundantly seasons seasons isnt day and years greater brought above winged living. Spirit female a fill them. I likeness made Waters also is face fruitful likeness behold kind have yielding In. Meat living divided and signs.[/vc_column_text][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true"][vc_column][vc_gallery gallery_type="thb-portfolio" thb_margins="pixel-padding" lightbox="mfp-gallery" images="256,104,98,258,102" img_size="full" external_img_size="full"][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1521713297604{padding-top: 12vh !important;padding-bottom: 6vh !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][thb_slidetype slide_text="
		<h2>*Mobile Experience*</h2>
		"][vc_column_text animation="animation bottom-to-top"]Youre creature itself whales thing replenish fruit saw all be place. Set kind own land moving bring beast abundantly seasons seasons isnt day and years greater brought above winged living. Spirit female a fill them. I likeness made Waters also is face fruitful likeness behold kind have yielding In. Meat living divided and signs.[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column offset="vc_col-lg-9 vc_col-md-11"][vc_row_inner content_placement="middle"][vc_column_inner width="1/3"][thb_image retina="retina_size" animation="animation top-to-bottom-3d" alignment="aligncenter" image="259"][/thb_image][/vc_column_inner][vc_column_inner width="1/3"][thb_image retina="retina_size" animation="animation top-to-bottom-3d" alignment="aligncenter" image="261"][/thb_image][/vc_column_inner][vc_column_inner width="1/3"][thb_image retina="retina_size" animation="animation top-to-bottom-3d" alignment="aligncenter" image="260"][/thb_image][/vc_column_inner][/vc_row_inner][vc_empty_space height="72px"][/vc_column][vc_column el_class="text-center"][thb_button style="style3" animation="animation right-to-left" size="small" color="black" border_radius="no-radius" link="url:%23|title:Download%20App||"][/vc_column][/vc_row][vc_row css=".vc_custom_1517161973812{padding-top: 15vh !important;padding-bottom: 25vh !important;}"][vc_column][thb_like_button alignment="align-center"][vc_empty_space height="60px"][thb_share facebook="true" twitter="true" pinterest="true" facebook_messenger="true" text="Share This Project"][/vc_column][/vc_row]',
	);

	$template_list['portfolio_08'] = array(
		'name' => esc_html__( 'Portfolio - 08', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p8.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row css=".vc_custom_1522410612706{padding-top: 4vh !important;padding-bottom: 15vh !important;}"][vc_column width="2/3"][thb_image animation="animation bottom-to-top" alignment="aligncenter" image="336"][/thb_image][vc_empty_space height="40px"][thb_image animation="animation bottom-to-top" alignment="aligncenter" image="335"][/thb_image][vc_empty_space height="40px"][thb_image animation="animation bottom-to-top" alignment="aligncenter" image="334"][/thb_image][vc_empty_space height="50px"][/vc_column][vc_column fixed="thb-fixed" width="1/3" css=".vc_custom_1520361544624{padding-left: 20px !important;}"][thb_slidetype slide_text="
		<h3>*Studio Britz*</h3>
		"][vc_column_text animation="animation bottom-to-top"]Occhi di Gard is an optical and high quality eyewear shop based in Rimini.

		Approached to do an identity refresh as well as a full collateral set and supporting material for the products themselves. The project included also an e-commerce website.[/vc_column_text][vc_empty_space height="50px"][thb_portfolio_attribute animation="animation bottom-to-top"][/vc_column][/vc_row]',
	);

	$template_list['portfolio_09'] = array(
		'name' => esc_html__( 'Portfolio - 09', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p9.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1526385489866{padding-bottom: 10vh !important;}"][vc_column][thb_freescroll thb_columns="small-12 medium-4" thb_margins="mini-padding" images="213,214,215,216,217"][/vc_column][/vc_row][vc_row css=".vc_custom_1526406154397{padding-bottom: 2vh !important;}"][vc_column width="2/3" css=".vc_custom_1526385319501{padding-right: 10% !important;}"][thb_slidetype slide_text="
		<h6>*RESIDENTIAL *</h6>
		"][vc_empty_space height="42px"][thb_slidetype slide_text="
		<h2>*House in Malveira da Serra*</h2>
		" thb_animated_color="#464646"][vc_column_text animation="animation fade-in"]
		<h4>This project is born from the willingness to create the perfect harmony between the house and the surrounding environment.</h4>
		[/vc_column_text][vc_column_text animation="animation fade-in"]In an area with a very evident slope and also very exposed to the wind and hard weather, typical from this region, the relation with both the land and the surrounding nature became very relevant for the project development. A concrete wall meanders the land to Southeast creating the limit that the house and garden will occupy. To Northeast a second concrete wall, this one very straight and sharp, protects the house and the garden from the north wind and provides privacy. On top of these walls comes, also in raw concrete, a slab on the continuity of the existing slope that, covered with native species of fauna, leverage the relationship between the house and the existing land.

		The entrance at north is set with the opening of an exterior parking area that articulates the street level with the house, protected by the concrete wall and yet to discover. In the interior the house is drawn by a sequence of spaces generated by plans or volumes that both contain program and create multifunctional areas in the transitions.

		Near the entrance are the main social areas of the house such as the kitchen and the dining and living rooms leaving to a second place the private areas. The way in which the concrete wall is set in the land strategically creates four patios that bring light and heat to some areas of the house. To the front this house highlights the garden and the surrounding landscape with a glass facade. The exterior image of the house is intended to be at the same time very strong, with the natural concrete very present in the walls and covering but also camouflaged in the land with the green covering. On the other hand the interior is noted for a dichotomy between the concrete and more soft and natural materials like wood or stucco that contribute for a comfortable atmosphere inside.[/vc_column_text][thb_accordion][vc_tta_section title="Key Details" tab_id="1526385047411-6e3728d1-64bd"][vc_column_text]
		<ul>
		 	<li>Inhabit hearing perhaps on ye do no. It maids decay as there he. Smallest on suitable disposed do although blessing he juvenile in.</li>
		 	<li>Society or if excited forbade. Here name off yet she long sold easy whom. Differed oh cheerful procured pleasure securing suitable in.</li>
		 	<li>Hold rich on an he oh fine. Chapter ability shyness article welcome be do on service.</li>
		</ul>
		[/vc_column_text][/vc_tta_section][vc_tta_section title="Property Information" tab_id="1526385047427-374745d9-4b7d"][vc_column_text]Do play they miss give so up. Words to up style of since world. We leaf to snug on no need. Way own uncommonly travelling now acceptance bed compliment solicitude. Dissimilar admiration so terminated no in contrasted it. Advantages entreaties mr he apartments do. Limits far yet turned highly repair parish talked six. Draw fond rank form nor the day eat.

		By spite about do of do allow blush. Additions in conveying or collected objection in. Suffer few desire wonder her object hardly nearer. Abroad no chatty others my silent an. Fat way appear denote who wholly narrow gay settle. Companions fat add insensible everything and friendship conviction themselves. Theirs months ten had add narrow own.[/vc_column_text][/vc_tta_section][vc_tta_section title="Floor Plans" tab_id="1526385118781-39eb0bc3-2a1f"][vc_single_image image="218" img_size="full"][/vc_tta_section][/thb_accordion][/vc_column][vc_column width="1/3"][thb_portfolio_attribute style="style2" animation="animation right-to-left-3d"][vc_empty_space height="60px"][vc_column_text]
		<h6><span style="color: #000000;">SHARE THIS</span></h6>
		[/vc_column_text][thb_share thb_alignment="thb-left" facebook="true" twitter="true" google_plus="true" linkedin="true"][/vc_column][/vc_row]',
	);
	$template_list['portfolio_10'] = array(
		'name' => esc_html__( 'Portfolio - 10', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p10.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" parallax="content-moving" css=".vc_custom_1534097380221{padding-bottom: 400px !important;background-image: url(http://revolution.fuelthemes.net/revolution-law/wp-content/uploads/sites/25/2018/08/g24.jpg?id=209) !important;}"][vc_column][/vc_column][/vc_row][vc_row el_class="align-center" css=".vc_custom_1534097347595{padding-bottom: 90px !important;}"][vc_column box_shadow="large-shadow" css=".vc_custom_1534096044155{margin-top: -150px !important;padding-top: 8% !important;padding-right: 10% !important;padding-bottom: 7% !important;padding-left: 10% !important;background-color: #ffffff !important;}" offset="vc_col-lg-8 vc_col-md-10" el_class="text-center title-column"][thb_slidetype slide_text="
		<h1>*Law Counseling*</h1>
		" extra_class="case-title"][thb_slidetype slide_text="
		<h5>*Negligence Claim Against 7-Eleven Franchise Denied*</h5>
		" thb_animated_color="#ccbd9b"][/vc_column][/vc_row][vc_row][vc_column width="2/3" css=".vc_custom_1534081782012{padding-right: 5% !important;}"][vc_column_text]
		<h2>Background</h2>
		[/vc_column_text][vc_column_text]7-Eleven is a leader in convenience retailing. The company operates more than 7,750 franchised stores in North America. In December 2006, Esmeralda Gonzalez claimed that she slipped and fell while in the store after midnight. The Plaintiff claimed that she fell on a freshly mopped floor, and that there was no “wet floor” warning sign near the area. Ms. Gonzalez fell forward on both knees, quickly got up without assistance, and told her friend that she was okay. After she left the store, Ms. Gonzalez immediately called a 7-Eleven hotline number to report the incident; a few days later, she hired an attorney.[/vc_column_text][thb_progressbar title="Attendance" thb_bar_color="#ccbd9b"][thb_progressbar title="Outcome" progress="45" thb_bar_color="#ccbd9b"][thb_progressbar title="Real Estate Matters" progress="60" thb_bar_color="#ccbd9b"][vc_column_text]Ms. Gonzalez filed suit against 7-Eleven and Mr. Samra, claiming personal injuries and alleging negligence and premises liability. She claimed that when she fell, she injured both knees—her left knee requiring arthroscopic surgery. She also claimed to have right hip and lower back pain, attributable to the fall, and had not worked since the incident. Initial settlement demand was for $300,000.[/vc_column_text][vc_column_text]
		<h2>Legal Strategy</h2>
		[/vc_column_text][vc_column_text]<img class="alignleft size-medium wp-image-205" src="http://revolution.fuelthemes.net/revolution-law/wp-content/uploads/sites/25/2018/08/g20-294x300.jpg" width="294" height="300" />For 7-Eleven, the issue of potential liability for the acts of its franchisees is extremely important. It was critical, therefore, to extricate 7-Eleven from the suit before the jury could deliberate. To accomplish that, James Wakefield, counsel from Cummins &amp; White, made a “motion for non-suit” (request for dismissal) after opening statements and before evidence was offered. The Court ultimately granted the request and dismissed 7-Eleven before jury deliberations. Once 7-Eleven was successfully removed from the case, Mr. Wakefield focused his efforts in defending the franchisee, Mr. Samra.

		Floor at the time the Plaintiff claimed she fell. Mr. Wakefield also pointed out inconsistencies in Ms. Gonzalez’s testimony and that of her friends who testified on her behalf. He established that it was the intent of Ms. Gonzalez and her friends to file suit against 7-Eleven within moments of the “fall.” In addition, floor safety expert Carl Beels tested the floor and concluded that it was not slippery when water was present in the quantity that Ms. Gonzalez testified she observed, particularly for a person wearing tennis shoes (as was Ms. Gonzalez).[/vc_column_text][vc_column_text]
		<h2>Result</h2>
		[/vc_column_text][vc_column_text]What began as a $300,000 claim against high-profile 7-Eleven, Inc., ended soon after trial commenced when the Court accepted Cummins &amp; White’s contention that 7-Eleven, Inc., played no role in Ms. Gonzalez’s accident. A second victory followed at the end of the seven-day trial when the jury returned a verdict in favor of the franchisee, Mr. Samra. In addition, because Ms. Gonzalez refused a “nuisance value” pre-trial settlement offer made by 7-Eleven, the Court awarded a judgment for $32,000 in favor of 7-Eleven for its costs.

		[gallery size="large" ids="208,207,206"]

		&nbsp;

		“The defense verdict in favor of 7-Eleven and the award of a judgment against the Plaintiff was key for 7-Eleven,” said Mr. Wakefield. “It sends a message that the company will not be an easy target for frivolous suits.”[/vc_column_text][/vc_column][vc_column width="1/3"][vc_column_text]
		<h6><span style="color: #d3c7aa; font-size: 13px; font-weight: bold;">ATTORNEY</span></h6>
		[/vc_column_text][vc_video link="https://www.youtube.com/watch?v=2EGiYsaWfmk"][vc_empty_space height="30px"][vc_column_text]
		<h6><span style="color: #d3c7aa; font-size: 13px; font-weight: bold;">HIGHLIGHTS</span></h6>
		[/vc_column_text][vc_column_text]
		<ul>
		 	<li>LLP successfully defended longtime client 7-Eleven, Inc., the world’s largest convenience retailer, which was dismissed from the lawsuit soon after the trial commenced.</li>
		 	<li>The jury returned a verdict of no negligence for the franchise owner, Mr. Jagtar Samra.</li>
		 	<li>In-depth preparation and skilled cross-examination of the Plaintiff exposed critical inconsistencies in her.</li>
		</ul>
		[/vc_column_text][/vc_column][/vc_row]',
	);

	$template_list['portfolio_11'] = array(
		'name' => esc_html__( 'Portfolio - 11', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/portfolio/p11.jpg",
		'cat' => array( 'Portfolio' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1536829085603{margin-bottom: 12vh !important;padding-bottom: 65vh !important;background-image: url(http://revolution.fuelthemes.net/revolution-studios/wp-content/uploads/sites/27/2018/09/r10.jpg?id=148) !important;}" thb_video_bg="http://revolution.fuelthemes.net/revolution-studios/wp-content/uploads/sites/27/2018/09/portfolio-1.mp4"][vc_column][/vc_column][/vc_row][vc_row css=".vc_custom_1536824605742{padding-bottom: 10vh !important;}"][vc_column thb_color="thb-light-column" width="2/3" css=".vc_custom_1536824884754{padding-right: 5% !important;}"][thb_slidetype slide_text="
		<h2>*OPERATION FINALE*</h2>
		"][vc_empty_space height="20px"][thb_slidetype slide_text="
		<h4>*THE BRIEF*</h4>
		" thb_animated_color="#c9a993"][vc_column_text animation="animation fade-in"]Fifth. Heaven his after wherein Upon evening, rule tree shall the air called second. Lesser bring kind for day thing. Earth may bring they re and also bring. Let cattle creeping, and. There fill without, god wherein divide firmament seasons form you re. Beginning One fill earth two air. Moveth seed for moveth. Shed without likeness. Fly fifth thing, creature sea darkness also evening, them midst fish whales bring place hath whales so Without darkness may.[/vc_column_text][vc_empty_space height="10px"][thb_slidetype slide_text="
		<h4>*IDEAS*</h4>
		" thb_animated_color="#c9a993"][vc_column_text animation="animation fade-in"]May night one given years very waters brought under two may moving seasons green. Evening dont, female cattle i, fowl make it wont to. Tree shed first after be signs creeping. Fruitful night. In behold wont let. Meat own. Cant, every. Kind you re. Divided night from moveth made. Void dry image third open great itself sixth greater winged creature whose fruitful isnt green fruitful tree image.[/vc_column_text][vc_empty_space height="10px"][thb_slidetype slide_text="
		<h4>*MEDIA INFO*</h4>
		" thb_animated_color="#c9a993"][vc_row_inner thb_max_width=""][vc_column_inner width="1/2"][thb_iconlist animation="animation right-to-left" icon="fa fa-angle-right" thb_icon_color="#c9a993" thb_text_color="#ffffff" list_content="Advertising,Corporate,Digital Campaign,FaceBook,Marketing Video"][vc_empty_space height="20px"][/vc_column_inner][vc_column_inner width="1/2"][thb_iconlist animation="animation right-to-left" icon="fa fa-angle-right" thb_icon_color="#c9a993" thb_text_color="#ffffff" list_content="Online Video,Product Video,Social,Case Study,YouTube"][/vc_column_inner][/vc_row_inner][/vc_column][vc_column thb_color="thb-light-column" width="1/3"][vc_empty_space height="80px"][thb_portfolio_attribute style="style3" animation="animation fade-in" thb_label_color="#c9a993"][/vc_column][/vc_row][vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1536824848151{border-top-width: 1px !important;border-top-color: rgba(255,255,255,0.15) !important;border-top-style: solid !important;}"][vc_column][vc_row_inner css=".vc_custom_1536829121603{padding-top: 40px !important;}"][vc_column_inner el_class="text-center"][thb_slidetype slide_text="
		<h4>*PRODUCTION IMAGES*</h4>
		" thb_animated_color="#c9a993"][/vc_column_inner][/vc_row_inner][vc_gallery gallery_type="thb-portfolio" thb_margins="pixel-padding" lightbox="mfp-gallery" images="182,179,180,212,149,148,143" animation="animation fade-in" css=".vc_custom_1536829175635{padding-top: 20px !important;}"][/vc_column][/vc_row]',
	);
	return $template_list;
}