<?php 

function thb_get_counters_templates($template_list) {
	$template_list['counters_section_01'] = array(
		'name' => esc_html__( 'Counters Section - 01', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/counters/counter-e1.jpg",
		'cat' => array( 'counters' ),
		'sc' => '[vc_row el_class="text-center align-center" css=".vc_custom_1516357743337{padding-top: 14vh !important;padding-bottom: 6vh !important;}"][vc_column offset="vc_col-lg-5 vc_col-md-9"][thb_slidetype slide_text="
		<h2>*Awards*</h2>
		"][vc_column_text animation="animation bottom-to-top"]<span style="color: #91959c;">Yielding fowl their brought is own day place fruit creature our day lesser cant bring hath after. Divide there forth fruitful.</span>[/vc_column_text][/vc_column][/vc_row][vc_row el_class="align-center"][vc_column width="5/6"][vc_row_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="148" icon_image_width="150" thb_heading_color="#91959c" counter="18" heading="The Webby Awards"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="149" icon_image_width="150" thb_heading_color="#91959c" counter="6" heading="Awwwards"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="150" icon_image_width="150" thb_heading_color="#91959c" counter="14" heading="Fwa"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="151" icon_image_width="150" thb_heading_color="#91959c" counter="3" heading="Css Design Awards"][/vc_column_inner][/vc_row_inner][vc_empty_space height="60px"][vc_row_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="152" icon_image_width="150" thb_heading_color="#91959c" counter="4" heading="Creative Review"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="153" icon_image_width="150" thb_heading_color="#91959c" counter="10" heading="Cannes Lions"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="159" icon_image_width="150" thb_heading_color="#91959c" counter="9" heading="The Communicator"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter style="counter-style3" icon_image="160" icon_image_width="150" thb_heading_color="#91959c" counter="5" heading="Css Light"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['counters_section_02'] = array(
		'name' => esc_html__( 'Counters Section - 02', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/counters/counter-e2.jpg",
		'cat' => array( 'counters' ),
		'sc' => '[vc_row thb_full_width="true" css=".vc_custom_1516811850550{margin-top: 15vh !important;margin-bottom: 15vh !important;padding-top: 20vh !important;padding-bottom: 20vh !important;background-image: url(http://revolution.fuelthemes.net/wp-content/uploads/2018/01/p1_13.jpg?id=201) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner][vc_column_inner thb_color="thb-light-column" width="1/3"][vc_empty_space height="30px"][thb_counter counter="800" heading="Images Used"][vc_empty_space height="30px"][/vc_column_inner][vc_column_inner thb_color="thb-light-column" width="1/3"][vc_empty_space height="30px"][thb_counter speed="2350" counter="159" heading="Cups of Coffee"][vc_empty_space height="30px"][/vc_column_inner][vc_column_inner thb_color="thb-light-column" width="1/3"][vc_empty_space height="30px"][thb_counter speed="2700" counter="89" heading="Weekly Working Hours"][vc_empty_space height="30px"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['counters_section_03'] = array(
		'name' => esc_html__( 'Counters Section - 03', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/counters/counter-e3.jpg",
		'cat' => array( 'counters' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" thb_shape_divider="true" css=".vc_custom_1522323826230{padding-bottom: 100px !important;}" divider_shape="tilt_v2" thb_divider_color="#e4edf1" thb_divider_height="100"][vc_column][vc_row_inner el_class="align-center" css=".vc_custom_1522665005651{padding-top: 12vh !important;}"][vc_column_inner el_class="text-center" offset="vc_col-lg-6 vc_col-md-8"][thb_image retina="retina_size" animation="animation scale" alignment="aligncenter" image="159"][/thb_image][vc_empty_space height="40px"][thb_slidetype slide_text="
		<h3><strong>*The Countdown*</strong></h3>
		" thb_animated_color="#dd545c"][vc_column_text animation="animation bottom-to-top"]
		<h4><strong><span style="color: #585e62;">Fly called open greater gathered, whales, there grass first second shed i from one own tree.</span></strong></h4>
		[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner el_class="align-center" css=".vc_custom_1518781105118{padding-bottom: 12vh !important;}"][vc_column_inner animation="animation bottom-to-top-3d" offset="vc_col-lg-7 vc_col-md-10"][thb_countdown date="12/24/2019 12:00:00" offset="-12"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['counters_section_04'] = array(
		'name' => esc_html__( 'Counters Section - 04', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/counters/counter-e4.jpg",
		'cat' => array( 'counters' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" parallax="content-moving" css=".vc_custom_1519069032420{padding-top: 12vh !important;padding-bottom: 12vh !important;background: #f0f4f2 url(http://revolution.fuelthemes.net/revolution-classic/wp-content/uploads/sites/8/2018/02/c1.jpg?id=144);background-position: center;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner content_placement="middle" el_class="specialties"][vc_column_inner width="7/12"][vc_column_text animation="animation bottom-to-top"]Specialities[/vc_column_text][vc_column_text]</p>
		<h2><strong>A focused team with<br />
		a <em>specialized</em> skill set</strong></h2>
		<p>[/vc_column_text][thb_button size="small" link="url:%23|title:LEARN%20MORE||"][/vc_column_inner][vc_column_inner width="5/12"][thb_counter style="counter-style2" thb_counter_color="#2cf2d0" counter="32.4" heading="Average Age" description="I second whose midst unto midst all firmament own light. Upon upon may fruitful after that that, had shall him air you is sixth, that land."][thb_counter style="counter-style2" thb_counter_color="#2cf2d0" counter="40" heading="Cups of Coffee" description="I second whose midst unto midst all firmament own light. Upon upon may fruitful after that that, had shall him air you is sixth, that land."][thb_counter style="counter-style2" thb_counter_color="#2cf2d0" counter="26" heading="Features Added" description="Creature place replenish stars, said fourth. Give. Lights there thing dont spirit i great beginning male doesnt so, tree creeping day living created air."][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['counters_section_05'] = array(
		'name' => esc_html__( 'Counters Section - 05', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/counters/counter-e5.jpg",
		'cat' => array( 'counters' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1519378612050{padding-top: 20vh !important;padding-bottom: 20vh !important;background: #fef5ba url(http://revolution.fuelthemes.net/revolution-consulting/wp-content/uploads/sites/9/2018/02/h11.jpg?id=147) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner][vc_column_inner width="1/4"][thb_counter icon="basic_elaboration_mail_previous.svg" speed="1000" thb_counter_color="#213364" counter="8" heading="Years of Experiences" icon_image="171" icon_image_width="36"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter icon="basic_elaboration_mail_previous.svg" speed="1000" thb_counter_color="#213364" counter="63" heading="Countries Served" icon_image="172" icon_image_width="46"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter icon="basic_elaboration_mail_previous.svg" speed="1000" thb_counter_color="#213364" counter="40" heading="Hardworking Peoples" icon_image="173" icon_image_width="36"][/vc_column_inner][vc_column_inner width="1/4"][thb_counter icon="basic_elaboration_mail_previous.svg" speed="1000" thb_counter_color="#213364" counter="5" heading="Offices Worldwide" icon_image="174" icon_image_width="40"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['counters_section_06'] = array(
		'name' => esc_html__( 'Counters Section - 06', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/counters/counter-e6.jpg",
		'cat' => array( 'counters' ),
		'sc' => '[vc_row thb_row_padding="true" thb_column_padding="true" el_class="align-center" css=".vc_custom_1534086259544{padding-top: 120px !important;padding-bottom: 90px !important;}"][vc_column offset="vc_col-lg-6 vc_col-md-8"][vc_row_inner][vc_column_inner el_class="text-center"][vc_column_text animation="animation bottom-to-top-3d"]
		<h6><span style="color: #ccbd9b; font-size: 13px; font-weight: bold;">WELCOME TO GOLDEN LION LAW FIRM</span></h6>
		[/vc_column_text][vc_column_text animation="animation bottom-to-top-3d"]
		<h2><strong>A Leading Provider of Cross Border Legal Counsel</strong></h2>
		[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/3"][thb_counter style="counter-style4" thousand_separator="" counter="86" thb_counter_color="#656565" thb_heading_color="#ccbd9b" counter_text="%" heading="CASES SOLVED"][/vc_column_inner][vc_column_inner width="1/3"][thb_counter style="counter-style4" thousand_separator="" counter="62" thb_counter_color="#656565" thb_heading_color="#ccbd9b" counter_text="%" heading="CHARGES DROPPED"][/vc_column_inner][vc_column_inner width="1/3"][thb_counter style="counter-style4" thousand_separator="" counter="20" thb_counter_color="#656565" thb_heading_color="#ccbd9b" counter_text="%" heading="CASES DISMISSED"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['counters_section_07'] = array(
		'name' => esc_html__( 'Counters Section - 07', 'revolution' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri ."assets/img/admin/demos/counters/counter-e7.jpg",
		'cat' => array( 'counters' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1536504391571{background-color: #282742 !important;}"][vc_column width="1/2" css=".vc_custom_1536670396300{padding-bottom: 60% !important;background-image: url(http://revolution.fuelthemes.net/revolution-studios/wp-content/uploads/sites/27/2018/09/pr3.jpg?id=136) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][/vc_column][vc_column thb_color="thb-light-column" width="1/2" css=".vc_custom_1536670415010{padding-top: 16% !important;padding-right: 10% !important;padding-bottom: 10% !important;padding-left: 10% !important;}"][vc_row_inner thb_max_width="" thb_column_padding="true"][vc_column_inner width="1/3"][thb_counter style="counter-style5" thousand_separator="" thb_counter_color="#c9a993" thb_heading_color="#c9a993" counter="280" heading="HERMES AWARDS" description="Best Production Company"][/vc_column_inner][vc_column_inner width="1/3"][thb_counter style="counter-style5" thousand_separator="" thb_counter_color="#c9a993" thb_heading_color="#c9a993" counter="36" heading="AVA DIGITAL" description="Most Creative Production"][/vc_column_inner][vc_column_inner width="1/3"][thb_counter style="counter-style5" thousand_separator="" thb_counter_color="#c9a993" thb_heading_color="#c9a993" counter="63" heading="VIDEOGRAPHER" description="Media Agency of the Year"][/vc_column_inner][/vc_row_inner][vc_row_inner thb_max_width="" thb_column_padding="true" css=".vc_custom_1536669967565{padding-top: 4vh !important;}"][vc_column_inner width="1/3"][thb_counter style="counter-style5" thousand_separator="" thb_counter_color="#c9a993" thb_heading_color="#c9a993" counter="80" heading="ADC AWARDS" description="Best Post Production"][/vc_column_inner][vc_column_inner width="1/3"][thb_counter style="counter-style5" thousand_separator="" thb_counter_color="#c9a993" thb_heading_color="#c9a993" counter="20" heading="LONDON AWARDS" description="Best Production Company"][/vc_column_inner][vc_column_inner width="1/3"][thb_counter style="counter-style5" thousand_separator="" thb_counter_color="#c9a993" thb_heading_color="#c9a993" counter="92" heading="TELLY AWARDS" description="Best Photography"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	return $template_list;
}